kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: e-com-hpa
  namespace: nginx
spec:
  scaleTargetRef:
    kind: Deployment
    name: e-com-app
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
